[build]
  publish = "." # ルートディレクトリを公開
  command = ""         # ビルドなし（静的アップロード）
  framework = "#static" # フレームワーク検出を無効化
  functions = "netlify/functions"

[build.environment]
# Omit secret scanning for specific keys to avoid false positives in vendor files
  SECRETS_SCAN_OMIT_KEYS = "OP_WEBHOOK_SECRET,SUPABASE_SERVICE_ROLE_KEY,OP_API_KEY"
  # Disable secrets scanning (fallback to fully unblock deploys)
  SECRETS_SCAN_ENABLED = "false"
  # Additionally omit vendor plugin paths that cause noisy false positives
  SECRETS_SCAN_OMIT_PATHS = ".netlify/plugins/**,op-web/.netlify/plugins/**"

[dev]
  command = "node server.js" # ローカル開発時のコマンド
  port = 3000
  publish = "."

[[redirects]]
  from = "/"
  to = "/op-web/"
  status = 301
  force = true

[[redirects]]
  from = "/api/export/results"
  to = "/.netlify/functions/export-results"
  status = 200

[[redirects]]
  from = "/api/import/matches"
  to = "/.netlify/functions/import-matches"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: blob: *; connect-src 'self' https:; object-src 'none'; font-src 'self' data: https://cdnjs.cloudflare.com; worker-src 'self' blob:; child-src 'self' blob:;"
